export interface ReportData {
  caseTitle: string;
  patientPhotoUrl?: string;
  workflowState: string;
  plan: {
    additiveBias: string;
    selectedTeeth: string[];
    treatmentMap: Record<string, string>;
  };
  variants: Array<{
    label: string;
    teethCount: number;
    avgWidth: number;
    avgHeight: number;
  }>;
  activeVariantLabel?: string;
  shadeId?: string;
  generatedAt: string;
}

/**
 * Generate a case report as an HTML string suitable for printing.
 * Uses window.print() for PDF generation (no external library needed).
 */
export function generateReportHtml(data: ReportData): string {
  const treatmentRows = data.plan.selectedTeeth
    .map((toothId) => {
      const treatment = data.plan.treatmentMap[toothId] ?? "veneer";
      const variant = data.variants.find((v) => v.label === data.activeVariantLabel);
      return `
        <tr>
          <td>${toothId}</td>
          <td>${treatment}</td>
          <td>${variant ? variant.avgWidth.toFixed(1) : "-"}</td>
          <td>${variant ? variant.avgHeight.toFixed(1) : "-"}</td>
        </tr>`;
    })
    .join("");

  const variantRows = data.variants
    .map((v) => {
      const isActive = v.label === data.activeVariantLabel;
      return `
        <tr${isActive ? ' style="font-weight: 600; background: #f0f7ff;"' : ""}>
          <td>${v.label}${isActive ? " (selected)" : ""}</td>
          <td>${v.teethCount}</td>
          <td>${v.avgWidth.toFixed(1)} mm</td>
          <td>${v.avgHeight.toFixed(1)} mm</td>
        </tr>`;
    })
    .join("");

  const photoSection = data.patientPhotoUrl
    ? `<div style="margin: 20px 0; text-align: center;">
        <img src="${data.patientPhotoUrl}" alt="Patient photo"
             style="max-width: 400px; max-height: 300px; border-radius: 8px; border: 1px solid #ddd;" />
      </div>`
    : "";

  const shadeSection = data.shadeId
    ? `<div style="margin: 16px 0;">
        <h3 style="margin-bottom: 8px;">Shade Selection</h3>
        <p style="font-size: 16px; font-weight: 600;">${data.shadeId}</p>
      </div>`
    : "";

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>SmileGen Case Report - ${escapeHtml(data.caseTitle)}</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Inter", sans-serif;
      max-width: 800px;
      margin: 0 auto;
      padding: 40px 24px;
      color: #1a1a1a;
      line-height: 1.6;
    }
    h1 { font-size: 24px; margin-bottom: 4px; }
    h2 { font-size: 18px; margin-top: 32px; margin-bottom: 12px; border-bottom: 2px solid #e0e0e0; padding-bottom: 6px; }
    h3 { font-size: 14px; color: #555; }
    table { width: 100%; border-collapse: collapse; margin: 12px 0; }
    th, td { padding: 8px 12px; text-align: left; border-bottom: 1px solid #e0e0e0; font-size: 13px; }
    th { background: #f5f5f5; font-weight: 600; text-transform: uppercase; font-size: 11px; letter-spacing: 0.04em; color: #666; }
    .header { display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 3px solid #00b4d8; padding-bottom: 16px; margin-bottom: 24px; }
    .header-brand { font-size: 28px; font-weight: 700; color: #00b4d8; }
    .header-meta { text-align: right; font-size: 12px; color: #666; }
    .footer { margin-top: 48px; padding-top: 16px; border-top: 1px solid #e0e0e0; font-size: 11px; color: #999; text-align: center; }
    .status-badge { display: inline-block; padding: 2px 10px; border-radius: 12px; font-size: 11px; font-weight: 500; background: #e8f4fd; color: #0077b6; }
    @media print {
      body { padding: 20px; }
      .no-print { display: none; }
    }
  </style>
</head>
<body>
  <div class="header">
    <div>
      <div class="header-brand">SmileGen</div>
      <h1>${escapeHtml(data.caseTitle)}</h1>
      <span class="status-badge">${escapeHtml(data.workflowState)}</span>
    </div>
    <div class="header-meta">
      <div>Generated: ${escapeHtml(data.generatedAt)}</div>
      <div>Additive Bias: ${escapeHtml(data.plan.additiveBias)}</div>
    </div>
  </div>

  ${photoSection}

  <h2>Treatment Plan</h2>
  <table>
    <thead>
      <tr>
        <th>Tooth #</th>
        <th>Treatment</th>
        <th>Width (mm)</th>
        <th>Height (mm)</th>
      </tr>
    </thead>
    <tbody>
      ${treatmentRows}
    </tbody>
  </table>

  <h2>Variant Summary</h2>
  <table>
    <thead>
      <tr>
        <th>Variant</th>
        <th>Teeth</th>
        <th>Avg Width</th>
        <th>Avg Height</th>
      </tr>
    </thead>
    <tbody>
      ${variantRows}
    </tbody>
  </table>

  ${shadeSection}

  <div class="footer">
    Generated by SmileGen
  </div>
</body>
</html>`;
}

/**
 * Open the report in a new window for printing/saving as PDF.
 */
export function openReportForPrint(data: ReportData): void {
  if (typeof window === "undefined") return;

  const html = generateReportHtml(data);
  const newWindow = window.open("", "_blank");
  if (!newWindow) return;

  newWindow.document.write(html);
  newWindow.document.close();
  newWindow.focus();
  newWindow.print();
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
